version: 2.1

orbs:
  atvise:
    executors:
      node:
        docker:
          - image: circleci/node:12.18.2

    commands:
      install-pnpm:
        steps:
          - run:
              name: Install pnpm
              command: sudo npm i -g pnpm@^5.4.0
      attach:
        steps:
          - checkout:
              path: ~/project
          - attach_workspace:
              at: ~/project

jobs:
  install:
    executor: atvise/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
            - v1-deps
      - atvise/install-pnpm
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: atvise/node
    steps:
      - atvise/attach
      - run:
          name: Run ESLint
          command: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - run:
          name: Check prettier
          command: npm run format -- --check
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

  build:
    executor: atvise/node
    steps:
      - atvise/attach
      - atvise/install-pnpm
      - run:
          name: Build packages
          command: pnpm run -r build

  package-sync:
    executor: atvise/node
    steps:
      - atvise/attach
      - run:
          name: Validate packages are in sync
          command: npm run test

workflows:
  version: 2

  default:
    jobs:
      - install
      - build:
          requires:
            - install
      - package-sync:
          requires:
            - install
      - lint:
          requires:
            - build
