name: upload schemas

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: schemas
          destination_dir: schemas
          commit_message: ${{ github.event.head_commit.message }} [ci skip]
